/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module full_adder(a, b, cin, sum, cout);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input a;
  wire a;
  input b;
  wire b;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output sum;
  wire sum;
  \$_NAND_  _4_ (
    .A(a),
    .B(cin),
    .Y(_1_)
  );
  \$_OR_  _5_ (
    .A(a),
    .B(cin),
    .Y(_2_)
  );
  \$_NAND_  _6_ (
    .A(_1_),
    .B(_2_),
    .Y(_3_)
  );
  \$_XNOR_  _7_ (
    .A(b),
    .B(_3_),
    .Y(sum)
  );
  \$_NAND_  _8_ (
    .A(b),
    .B(_2_),
    .Y(_0_)
  );
  \$_NAND_  _9_ (
    .A(_1_),
    .B(_0_),
    .Y(cout)
  );
endmodule