/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "rca_24bit.v:1.1-36.10" *)
module rca_24bit(A, B, Cin, Sum, Cout);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  (* src = "rca_24bit.v:2.19-2.20" *)
  input [23:0] A;
  wire [23:0] A;
  (* src = "rca_24bit.v:3.19-3.20" *)
  input [23:0] B;
  wire [23:0] B;
  (* src = "rca_24bit.v:4.12-4.15" *)
  input Cin;
  wire Cin;
  (* src = "rca_24bit.v:6.12-6.16" *)
  output Cout;
  wire Cout;
  (* src = "rca_24bit.v:5.19-5.22" *)
  output [23:0] Sum;
  wire [23:0] Sum;
  (* hdlname = "adder_stage[0].genblk1.fa a" *)
  (* src = "rca_24bit.v:15.28-21.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[0].genblk1.fa.a ;
  (* hdlname = "adder_stage[0].genblk1.fa b" *)
  (* src = "rca_24bit.v:15.28-21.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[0].genblk1.fa.b ;
  (* hdlname = "adder_stage[0].genblk1.fa cin" *)
  (* src = "rca_24bit.v:15.28-21.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[0].genblk1.fa.cin ;
  (* hdlname = "adder_stage[0].genblk1.fa cout" *)
  (* src = "rca_24bit.v:15.28-21.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[0].genblk1.fa.cout ;
  (* hdlname = "adder_stage[0].genblk1.fa sum" *)
  (* src = "rca_24bit.v:15.28-21.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[0].genblk1.fa.sum ;
  (* hdlname = "adder_stage[10].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[10].genblk1.fa.a ;
  (* hdlname = "adder_stage[10].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[10].genblk1.fa.b ;
  (* hdlname = "adder_stage[10].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[10].genblk1.fa.cin ;
  (* hdlname = "adder_stage[10].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[10].genblk1.fa.cout ;
  (* hdlname = "adder_stage[10].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[10].genblk1.fa.sum ;
  (* hdlname = "adder_stage[11].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[11].genblk1.fa.a ;
  (* hdlname = "adder_stage[11].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[11].genblk1.fa.b ;
  (* hdlname = "adder_stage[11].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[11].genblk1.fa.cin ;
  (* hdlname = "adder_stage[11].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[11].genblk1.fa.cout ;
  (* hdlname = "adder_stage[11].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[11].genblk1.fa.sum ;
  (* hdlname = "adder_stage[12].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[12].genblk1.fa.a ;
  (* hdlname = "adder_stage[12].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[12].genblk1.fa.b ;
  (* hdlname = "adder_stage[12].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[12].genblk1.fa.cin ;
  (* hdlname = "adder_stage[12].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[12].genblk1.fa.cout ;
  (* hdlname = "adder_stage[12].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[12].genblk1.fa.sum ;
  (* hdlname = "adder_stage[13].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[13].genblk1.fa.a ;
  (* hdlname = "adder_stage[13].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[13].genblk1.fa.b ;
  (* hdlname = "adder_stage[13].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[13].genblk1.fa.cin ;
  (* hdlname = "adder_stage[13].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[13].genblk1.fa.cout ;
  (* hdlname = "adder_stage[13].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[13].genblk1.fa.sum ;
  (* hdlname = "adder_stage[14].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[14].genblk1.fa.a ;
  (* hdlname = "adder_stage[14].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[14].genblk1.fa.b ;
  (* hdlname = "adder_stage[14].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[14].genblk1.fa.cin ;
  (* hdlname = "adder_stage[14].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[14].genblk1.fa.cout ;
  (* hdlname = "adder_stage[14].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[14].genblk1.fa.sum ;
  (* hdlname = "adder_stage[15].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[15].genblk1.fa.a ;
  (* hdlname = "adder_stage[15].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[15].genblk1.fa.b ;
  (* hdlname = "adder_stage[15].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[15].genblk1.fa.cin ;
  (* hdlname = "adder_stage[15].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[15].genblk1.fa.cout ;
  (* hdlname = "adder_stage[15].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[15].genblk1.fa.sum ;
  (* hdlname = "adder_stage[16].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[16].genblk1.fa.a ;
  (* hdlname = "adder_stage[16].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[16].genblk1.fa.b ;
  (* hdlname = "adder_stage[16].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[16].genblk1.fa.cin ;
  (* hdlname = "adder_stage[16].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[16].genblk1.fa.cout ;
  (* hdlname = "adder_stage[16].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[16].genblk1.fa.sum ;
  (* hdlname = "adder_stage[17].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[17].genblk1.fa.a ;
  (* hdlname = "adder_stage[17].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[17].genblk1.fa.b ;
  (* hdlname = "adder_stage[17].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[17].genblk1.fa.cin ;
  (* hdlname = "adder_stage[17].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[17].genblk1.fa.cout ;
  (* hdlname = "adder_stage[17].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[17].genblk1.fa.sum ;
  (* hdlname = "adder_stage[18].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[18].genblk1.fa.a ;
  (* hdlname = "adder_stage[18].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[18].genblk1.fa.b ;
  (* hdlname = "adder_stage[18].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[18].genblk1.fa.cin ;
  (* hdlname = "adder_stage[18].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[18].genblk1.fa.cout ;
  (* hdlname = "adder_stage[18].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[18].genblk1.fa.sum ;
  (* hdlname = "adder_stage[19].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[19].genblk1.fa.a ;
  (* hdlname = "adder_stage[19].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[19].genblk1.fa.b ;
  (* hdlname = "adder_stage[19].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[19].genblk1.fa.cin ;
  (* hdlname = "adder_stage[19].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[19].genblk1.fa.cout ;
  (* hdlname = "adder_stage[19].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[19].genblk1.fa.sum ;
  (* hdlname = "adder_stage[1].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[1].genblk1.fa.a ;
  (* hdlname = "adder_stage[1].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[1].genblk1.fa.b ;
  (* hdlname = "adder_stage[1].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[1].genblk1.fa.cin ;
  (* hdlname = "adder_stage[1].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[1].genblk1.fa.cout ;
  (* hdlname = "adder_stage[1].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[1].genblk1.fa.sum ;
  (* hdlname = "adder_stage[20].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[20].genblk1.fa.a ;
  (* hdlname = "adder_stage[20].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[20].genblk1.fa.b ;
  (* hdlname = "adder_stage[20].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[20].genblk1.fa.cin ;
  (* hdlname = "adder_stage[20].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[20].genblk1.fa.cout ;
  (* hdlname = "adder_stage[20].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[20].genblk1.fa.sum ;
  (* hdlname = "adder_stage[21].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[21].genblk1.fa.a ;
  (* hdlname = "adder_stage[21].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[21].genblk1.fa.b ;
  (* hdlname = "adder_stage[21].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[21].genblk1.fa.cin ;
  (* hdlname = "adder_stage[21].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[21].genblk1.fa.cout ;
  (* hdlname = "adder_stage[21].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[21].genblk1.fa.sum ;
  (* hdlname = "adder_stage[22].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[22].genblk1.fa.a ;
  (* hdlname = "adder_stage[22].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[22].genblk1.fa.b ;
  (* hdlname = "adder_stage[22].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[22].genblk1.fa.cin ;
  (* hdlname = "adder_stage[22].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[22].genblk1.fa.cout ;
  (* hdlname = "adder_stage[22].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[22].genblk1.fa.sum ;
  (* hdlname = "adder_stage[23].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[23].genblk1.fa.a ;
  (* hdlname = "adder_stage[23].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[23].genblk1.fa.b ;
  (* hdlname = "adder_stage[23].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[23].genblk1.fa.cin ;
  (* hdlname = "adder_stage[23].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[23].genblk1.fa.cout ;
  (* hdlname = "adder_stage[23].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[23].genblk1.fa.sum ;
  (* hdlname = "adder_stage[2].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[2].genblk1.fa.a ;
  (* hdlname = "adder_stage[2].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[2].genblk1.fa.b ;
  (* hdlname = "adder_stage[2].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[2].genblk1.fa.cin ;
  (* hdlname = "adder_stage[2].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[2].genblk1.fa.cout ;
  (* hdlname = "adder_stage[2].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[2].genblk1.fa.sum ;
  (* hdlname = "adder_stage[3].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[3].genblk1.fa.a ;
  (* hdlname = "adder_stage[3].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[3].genblk1.fa.b ;
  (* hdlname = "adder_stage[3].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[3].genblk1.fa.cin ;
  (* hdlname = "adder_stage[3].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[3].genblk1.fa.cout ;
  (* hdlname = "adder_stage[3].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[3].genblk1.fa.sum ;
  (* hdlname = "adder_stage[4].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[4].genblk1.fa.a ;
  (* hdlname = "adder_stage[4].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[4].genblk1.fa.b ;
  (* hdlname = "adder_stage[4].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[4].genblk1.fa.cin ;
  (* hdlname = "adder_stage[4].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[4].genblk1.fa.cout ;
  (* hdlname = "adder_stage[4].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[4].genblk1.fa.sum ;
  (* hdlname = "adder_stage[5].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[5].genblk1.fa.a ;
  (* hdlname = "adder_stage[5].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[5].genblk1.fa.b ;
  (* hdlname = "adder_stage[5].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[5].genblk1.fa.cin ;
  (* hdlname = "adder_stage[5].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[5].genblk1.fa.cout ;
  (* hdlname = "adder_stage[5].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[5].genblk1.fa.sum ;
  (* hdlname = "adder_stage[6].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[6].genblk1.fa.a ;
  (* hdlname = "adder_stage[6].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[6].genblk1.fa.b ;
  (* hdlname = "adder_stage[6].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[6].genblk1.fa.cin ;
  (* hdlname = "adder_stage[6].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[6].genblk1.fa.cout ;
  (* hdlname = "adder_stage[6].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[6].genblk1.fa.sum ;
  (* hdlname = "adder_stage[7].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[7].genblk1.fa.a ;
  (* hdlname = "adder_stage[7].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[7].genblk1.fa.b ;
  (* hdlname = "adder_stage[7].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[7].genblk1.fa.cin ;
  (* hdlname = "adder_stage[7].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[7].genblk1.fa.cout ;
  (* hdlname = "adder_stage[7].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[7].genblk1.fa.sum ;
  (* hdlname = "adder_stage[8].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[8].genblk1.fa.a ;
  (* hdlname = "adder_stage[8].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[8].genblk1.fa.b ;
  (* hdlname = "adder_stage[8].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[8].genblk1.fa.cin ;
  (* hdlname = "adder_stage[8].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[8].genblk1.fa.cout ;
  (* hdlname = "adder_stage[8].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[8].genblk1.fa.sum ;
  (* hdlname = "adder_stage[9].genblk1.fa a" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:39.11-39.12" *)
  wire \adder_stage[9].genblk1.fa.a ;
  (* hdlname = "adder_stage[9].genblk1.fa b" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:40.11-40.12" *)
  wire \adder_stage[9].genblk1.fa.b ;
  (* hdlname = "adder_stage[9].genblk1.fa cin" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:41.11-41.14" *)
  wire \adder_stage[9].genblk1.fa.cin ;
  (* hdlname = "adder_stage[9].genblk1.fa cout" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:43.12-43.16" *)
  wire \adder_stage[9].genblk1.fa.cout ;
  (* hdlname = "adder_stage[9].genblk1.fa sum" *)
  (* src = "rca_24bit.v:24.28-30.18|rca_24bit.v:42.12-42.15" *)
  wire \adder_stage[9].genblk1.fa.sum ;
  (* src = "rca_24bit.v:8.17-8.22" *)
  wire [23:0] carry;
  assign _002_ = \adder_stage[0].genblk1.fa.b  ^ \adder_stage[0].genblk1.fa.a ;
  assign \adder_stage[0].genblk1.fa.sum  = _002_ ^ \adder_stage[0].genblk1.fa.cin ;
  assign _003_ = \adder_stage[0].genblk1.fa.b  & \adder_stage[0].genblk1.fa.a ;
  assign _004_ = \adder_stage[0].genblk1.fa.cin  & \adder_stage[0].genblk1.fa.b ;
  assign _000_ = _004_ | _003_;
  assign _001_ = \adder_stage[0].genblk1.fa.cin  & \adder_stage[0].genblk1.fa.a ;
  assign \adder_stage[0].genblk1.fa.cout  = _001_ | _000_;
  assign _007_ = \adder_stage[10].genblk1.fa.b  ^ \adder_stage[10].genblk1.fa.a ;
  assign \adder_stage[10].genblk1.fa.sum  = _007_ ^ \adder_stage[10].genblk1.fa.cin ;
  assign _008_ = \adder_stage[10].genblk1.fa.b  & \adder_stage[10].genblk1.fa.a ;
  assign _009_ = \adder_stage[10].genblk1.fa.cin  & \adder_stage[10].genblk1.fa.b ;
  assign _005_ = _009_ | _008_;
  assign _006_ = \adder_stage[10].genblk1.fa.cin  & \adder_stage[10].genblk1.fa.a ;
  assign \adder_stage[10].genblk1.fa.cout  = _006_ | _005_;
  assign _012_ = \adder_stage[11].genblk1.fa.b  ^ \adder_stage[11].genblk1.fa.a ;
  assign \adder_stage[11].genblk1.fa.sum  = _012_ ^ \adder_stage[11].genblk1.fa.cin ;
  assign _013_ = \adder_stage[11].genblk1.fa.b  & \adder_stage[11].genblk1.fa.a ;
  assign _014_ = \adder_stage[11].genblk1.fa.cin  & \adder_stage[11].genblk1.fa.b ;
  assign _010_ = _014_ | _013_;
  assign _011_ = \adder_stage[11].genblk1.fa.cin  & \adder_stage[11].genblk1.fa.a ;
  assign \adder_stage[11].genblk1.fa.cout  = _011_ | _010_;
  assign _017_ = \adder_stage[12].genblk1.fa.b  ^ \adder_stage[12].genblk1.fa.a ;
  assign \adder_stage[12].genblk1.fa.sum  = _017_ ^ \adder_stage[12].genblk1.fa.cin ;
  assign _018_ = \adder_stage[12].genblk1.fa.b  & \adder_stage[12].genblk1.fa.a ;
  assign _019_ = \adder_stage[12].genblk1.fa.cin  & \adder_stage[12].genblk1.fa.b ;
  assign _015_ = _019_ | _018_;
  assign _016_ = \adder_stage[12].genblk1.fa.cin  & \adder_stage[12].genblk1.fa.a ;
  assign \adder_stage[12].genblk1.fa.cout  = _016_ | _015_;
  assign _022_ = \adder_stage[13].genblk1.fa.b  ^ \adder_stage[13].genblk1.fa.a ;
  assign \adder_stage[13].genblk1.fa.sum  = _022_ ^ \adder_stage[13].genblk1.fa.cin ;
  assign _023_ = \adder_stage[13].genblk1.fa.b  & \adder_stage[13].genblk1.fa.a ;
  assign _024_ = \adder_stage[13].genblk1.fa.cin  & \adder_stage[13].genblk1.fa.b ;
  assign _020_ = _024_ | _023_;
  assign _021_ = \adder_stage[13].genblk1.fa.cin  & \adder_stage[13].genblk1.fa.a ;
  assign \adder_stage[13].genblk1.fa.cout  = _021_ | _020_;
  assign _027_ = \adder_stage[14].genblk1.fa.b  ^ \adder_stage[14].genblk1.fa.a ;
  assign \adder_stage[14].genblk1.fa.sum  = _027_ ^ \adder_stage[14].genblk1.fa.cin ;
  assign _028_ = \adder_stage[14].genblk1.fa.b  & \adder_stage[14].genblk1.fa.a ;
  assign _029_ = \adder_stage[14].genblk1.fa.cin  & \adder_stage[14].genblk1.fa.b ;
  assign _025_ = _029_ | _028_;
  assign _026_ = \adder_stage[14].genblk1.fa.cin  & \adder_stage[14].genblk1.fa.a ;
  assign \adder_stage[14].genblk1.fa.cout  = _026_ | _025_;
  assign _032_ = \adder_stage[15].genblk1.fa.b  ^ \adder_stage[15].genblk1.fa.a ;
  assign \adder_stage[15].genblk1.fa.sum  = _032_ ^ \adder_stage[15].genblk1.fa.cin ;
  assign _033_ = \adder_stage[15].genblk1.fa.b  & \adder_stage[15].genblk1.fa.a ;
  assign _034_ = \adder_stage[15].genblk1.fa.cin  & \adder_stage[15].genblk1.fa.b ;
  assign _030_ = _034_ | _033_;
  assign _031_ = \adder_stage[15].genblk1.fa.cin  & \adder_stage[15].genblk1.fa.a ;
  assign \adder_stage[15].genblk1.fa.cout  = _031_ | _030_;
  assign _037_ = \adder_stage[16].genblk1.fa.b  ^ \adder_stage[16].genblk1.fa.a ;
  assign \adder_stage[16].genblk1.fa.sum  = _037_ ^ \adder_stage[16].genblk1.fa.cin ;
  assign _038_ = \adder_stage[16].genblk1.fa.b  & \adder_stage[16].genblk1.fa.a ;
  assign _039_ = \adder_stage[16].genblk1.fa.cin  & \adder_stage[16].genblk1.fa.b ;
  assign _035_ = _039_ | _038_;
  assign _036_ = \adder_stage[16].genblk1.fa.cin  & \adder_stage[16].genblk1.fa.a ;
  assign \adder_stage[16].genblk1.fa.cout  = _036_ | _035_;
  assign _042_ = \adder_stage[17].genblk1.fa.b  ^ \adder_stage[17].genblk1.fa.a ;
  assign \adder_stage[17].genblk1.fa.sum  = _042_ ^ \adder_stage[17].genblk1.fa.cin ;
  assign _043_ = \adder_stage[17].genblk1.fa.b  & \adder_stage[17].genblk1.fa.a ;
  assign _044_ = \adder_stage[17].genblk1.fa.cin  & \adder_stage[17].genblk1.fa.b ;
  assign _040_ = _044_ | _043_;
  assign _041_ = \adder_stage[17].genblk1.fa.cin  & \adder_stage[17].genblk1.fa.a ;
  assign \adder_stage[17].genblk1.fa.cout  = _041_ | _040_;
  assign _047_ = \adder_stage[18].genblk1.fa.b  ^ \adder_stage[18].genblk1.fa.a ;
  assign \adder_stage[18].genblk1.fa.sum  = _047_ ^ \adder_stage[18].genblk1.fa.cin ;
  assign _048_ = \adder_stage[18].genblk1.fa.b  & \adder_stage[18].genblk1.fa.a ;
  assign _049_ = \adder_stage[18].genblk1.fa.cin  & \adder_stage[18].genblk1.fa.b ;
  assign _045_ = _049_ | _048_;
  assign _046_ = \adder_stage[18].genblk1.fa.cin  & \adder_stage[18].genblk1.fa.a ;
  assign \adder_stage[18].genblk1.fa.cout  = _046_ | _045_;
  assign _052_ = \adder_stage[19].genblk1.fa.b  ^ \adder_stage[19].genblk1.fa.a ;
  assign \adder_stage[19].genblk1.fa.sum  = _052_ ^ \adder_stage[19].genblk1.fa.cin ;
  assign _053_ = \adder_stage[19].genblk1.fa.b  & \adder_stage[19].genblk1.fa.a ;
  assign _054_ = \adder_stage[19].genblk1.fa.cin  & \adder_stage[19].genblk1.fa.b ;
  assign _050_ = _054_ | _053_;
  assign _051_ = \adder_stage[19].genblk1.fa.cin  & \adder_stage[19].genblk1.fa.a ;
  assign \adder_stage[19].genblk1.fa.cout  = _051_ | _050_;
  assign _057_ = \adder_stage[1].genblk1.fa.b  ^ \adder_stage[1].genblk1.fa.a ;
  assign \adder_stage[1].genblk1.fa.sum  = _057_ ^ \adder_stage[1].genblk1.fa.cin ;
  assign _058_ = \adder_stage[1].genblk1.fa.b  & \adder_stage[1].genblk1.fa.a ;
  assign _059_ = \adder_stage[1].genblk1.fa.cin  & \adder_stage[1].genblk1.fa.b ;
  assign _055_ = _059_ | _058_;
  assign _056_ = \adder_stage[1].genblk1.fa.cin  & \adder_stage[1].genblk1.fa.a ;
  assign \adder_stage[1].genblk1.fa.cout  = _056_ | _055_;
  assign _062_ = \adder_stage[20].genblk1.fa.b  ^ \adder_stage[20].genblk1.fa.a ;
  assign \adder_stage[20].genblk1.fa.sum  = _062_ ^ \adder_stage[20].genblk1.fa.cin ;
  assign _063_ = \adder_stage[20].genblk1.fa.b  & \adder_stage[20].genblk1.fa.a ;
  assign _064_ = \adder_stage[20].genblk1.fa.cin  & \adder_stage[20].genblk1.fa.b ;
  assign _060_ = _064_ | _063_;
  assign _061_ = \adder_stage[20].genblk1.fa.cin  & \adder_stage[20].genblk1.fa.a ;
  assign \adder_stage[20].genblk1.fa.cout  = _061_ | _060_;
  assign _067_ = \adder_stage[21].genblk1.fa.b  ^ \adder_stage[21].genblk1.fa.a ;
  assign \adder_stage[21].genblk1.fa.sum  = _067_ ^ \adder_stage[21].genblk1.fa.cin ;
  assign _068_ = \adder_stage[21].genblk1.fa.b  & \adder_stage[21].genblk1.fa.a ;
  assign _069_ = \adder_stage[21].genblk1.fa.cin  & \adder_stage[21].genblk1.fa.b ;
  assign _065_ = _069_ | _068_;
  assign _066_ = \adder_stage[21].genblk1.fa.cin  & \adder_stage[21].genblk1.fa.a ;
  assign \adder_stage[21].genblk1.fa.cout  = _066_ | _065_;
  assign _072_ = \adder_stage[22].genblk1.fa.b  ^ \adder_stage[22].genblk1.fa.a ;
  assign \adder_stage[22].genblk1.fa.sum  = _072_ ^ \adder_stage[22].genblk1.fa.cin ;
  assign _073_ = \adder_stage[22].genblk1.fa.b  & \adder_stage[22].genblk1.fa.a ;
  assign _074_ = \adder_stage[22].genblk1.fa.cin  & \adder_stage[22].genblk1.fa.b ;
  assign _070_ = _074_ | _073_;
  assign _071_ = \adder_stage[22].genblk1.fa.cin  & \adder_stage[22].genblk1.fa.a ;
  assign \adder_stage[22].genblk1.fa.cout  = _071_ | _070_;
  assign _077_ = \adder_stage[23].genblk1.fa.b  ^ \adder_stage[23].genblk1.fa.a ;
  assign \adder_stage[23].genblk1.fa.sum  = _077_ ^ \adder_stage[23].genblk1.fa.cin ;
  assign _078_ = \adder_stage[23].genblk1.fa.b  & \adder_stage[23].genblk1.fa.a ;
  assign _079_ = \adder_stage[23].genblk1.fa.cin  & \adder_stage[23].genblk1.fa.b ;
  assign _075_ = _079_ | _078_;
  assign _076_ = \adder_stage[23].genblk1.fa.cin  & \adder_stage[23].genblk1.fa.a ;
  assign \adder_stage[23].genblk1.fa.cout  = _076_ | _075_;
  assign _082_ = \adder_stage[2].genblk1.fa.b  ^ \adder_stage[2].genblk1.fa.a ;
  assign \adder_stage[2].genblk1.fa.sum  = _082_ ^ \adder_stage[2].genblk1.fa.cin ;
  assign _083_ = \adder_stage[2].genblk1.fa.b  & \adder_stage[2].genblk1.fa.a ;
  assign _084_ = \adder_stage[2].genblk1.fa.cin  & \adder_stage[2].genblk1.fa.b ;
  assign _080_ = _084_ | _083_;
  assign _081_ = \adder_stage[2].genblk1.fa.cin  & \adder_stage[2].genblk1.fa.a ;
  assign \adder_stage[2].genblk1.fa.cout  = _081_ | _080_;
  assign _087_ = \adder_stage[3].genblk1.fa.b  ^ \adder_stage[3].genblk1.fa.a ;
  assign \adder_stage[3].genblk1.fa.sum  = _087_ ^ \adder_stage[3].genblk1.fa.cin ;
  assign _088_ = \adder_stage[3].genblk1.fa.b  & \adder_stage[3].genblk1.fa.a ;
  assign _089_ = \adder_stage[3].genblk1.fa.cin  & \adder_stage[3].genblk1.fa.b ;
  assign _085_ = _089_ | _088_;
  assign _086_ = \adder_stage[3].genblk1.fa.cin  & \adder_stage[3].genblk1.fa.a ;
  assign \adder_stage[3].genblk1.fa.cout  = _086_ | _085_;
  assign _092_ = \adder_stage[4].genblk1.fa.b  ^ \adder_stage[4].genblk1.fa.a ;
  assign \adder_stage[4].genblk1.fa.sum  = _092_ ^ \adder_stage[4].genblk1.fa.cin ;
  assign _093_ = \adder_stage[4].genblk1.fa.b  & \adder_stage[4].genblk1.fa.a ;
  assign _094_ = \adder_stage[4].genblk1.fa.cin  & \adder_stage[4].genblk1.fa.b ;
  assign _090_ = _094_ | _093_;
  assign _091_ = \adder_stage[4].genblk1.fa.cin  & \adder_stage[4].genblk1.fa.a ;
  assign \adder_stage[4].genblk1.fa.cout  = _091_ | _090_;
  assign _097_ = \adder_stage[5].genblk1.fa.b  ^ \adder_stage[5].genblk1.fa.a ;
  assign \adder_stage[5].genblk1.fa.sum  = _097_ ^ \adder_stage[5].genblk1.fa.cin ;
  assign _098_ = \adder_stage[5].genblk1.fa.b  & \adder_stage[5].genblk1.fa.a ;
  assign _099_ = \adder_stage[5].genblk1.fa.cin  & \adder_stage[5].genblk1.fa.b ;
  assign _095_ = _099_ | _098_;
  assign _096_ = \adder_stage[5].genblk1.fa.cin  & \adder_stage[5].genblk1.fa.a ;
  assign \adder_stage[5].genblk1.fa.cout  = _096_ | _095_;
  assign _102_ = \adder_stage[6].genblk1.fa.b  ^ \adder_stage[6].genblk1.fa.a ;
  assign \adder_stage[6].genblk1.fa.sum  = _102_ ^ \adder_stage[6].genblk1.fa.cin ;
  assign _103_ = \adder_stage[6].genblk1.fa.b  & \adder_stage[6].genblk1.fa.a ;
  assign _104_ = \adder_stage[6].genblk1.fa.cin  & \adder_stage[6].genblk1.fa.b ;
  assign _100_ = _104_ | _103_;
  assign _101_ = \adder_stage[6].genblk1.fa.cin  & \adder_stage[6].genblk1.fa.a ;
  assign \adder_stage[6].genblk1.fa.cout  = _101_ | _100_;
  assign _107_ = \adder_stage[7].genblk1.fa.b  ^ \adder_stage[7].genblk1.fa.a ;
  assign \adder_stage[7].genblk1.fa.sum  = _107_ ^ \adder_stage[7].genblk1.fa.cin ;
  assign _108_ = \adder_stage[7].genblk1.fa.b  & \adder_stage[7].genblk1.fa.a ;
  assign _109_ = \adder_stage[7].genblk1.fa.cin  & \adder_stage[7].genblk1.fa.b ;
  assign _105_ = _109_ | _108_;
  assign _106_ = \adder_stage[7].genblk1.fa.cin  & \adder_stage[7].genblk1.fa.a ;
  assign \adder_stage[7].genblk1.fa.cout  = _106_ | _105_;
  assign _112_ = \adder_stage[8].genblk1.fa.b  ^ \adder_stage[8].genblk1.fa.a ;
  assign \adder_stage[8].genblk1.fa.sum  = _112_ ^ \adder_stage[8].genblk1.fa.cin ;
  assign _113_ = \adder_stage[8].genblk1.fa.b  & \adder_stage[8].genblk1.fa.a ;
  assign _114_ = \adder_stage[8].genblk1.fa.cin  & \adder_stage[8].genblk1.fa.b ;
  assign _110_ = _114_ | _113_;
  assign _111_ = \adder_stage[8].genblk1.fa.cin  & \adder_stage[8].genblk1.fa.a ;
  assign \adder_stage[8].genblk1.fa.cout  = _111_ | _110_;
  assign _117_ = \adder_stage[9].genblk1.fa.b  ^ \adder_stage[9].genblk1.fa.a ;
  assign \adder_stage[9].genblk1.fa.sum  = _117_ ^ \adder_stage[9].genblk1.fa.cin ;
  assign _118_ = \adder_stage[9].genblk1.fa.b  & \adder_stage[9].genblk1.fa.a ;
  assign _119_ = \adder_stage[9].genblk1.fa.cin  & \adder_stage[9].genblk1.fa.b ;
  assign _115_ = _119_ | _118_;
  assign _116_ = \adder_stage[9].genblk1.fa.cin  & \adder_stage[9].genblk1.fa.a ;
  assign \adder_stage[9].genblk1.fa.cout  = _116_ | _115_;
  assign carry[23] = Cout;
  assign \adder_stage[9].genblk1.fa.a  = A[9];
  assign \adder_stage[9].genblk1.fa.b  = B[9];
  assign \adder_stage[9].genblk1.fa.cin  = carry[8];
  assign carry[9] = \adder_stage[9].genblk1.fa.cout ;
  assign Sum[9] = \adder_stage[9].genblk1.fa.sum ;
  assign \adder_stage[8].genblk1.fa.a  = A[8];
  assign \adder_stage[8].genblk1.fa.b  = B[8];
  assign \adder_stage[8].genblk1.fa.cin  = carry[7];
  assign carry[8] = \adder_stage[8].genblk1.fa.cout ;
  assign Sum[8] = \adder_stage[8].genblk1.fa.sum ;
  assign \adder_stage[7].genblk1.fa.a  = A[7];
  assign \adder_stage[7].genblk1.fa.b  = B[7];
  assign \adder_stage[7].genblk1.fa.cin  = carry[6];
  assign carry[7] = \adder_stage[7].genblk1.fa.cout ;
  assign Sum[7] = \adder_stage[7].genblk1.fa.sum ;
  assign \adder_stage[6].genblk1.fa.a  = A[6];
  assign \adder_stage[6].genblk1.fa.b  = B[6];
  assign \adder_stage[6].genblk1.fa.cin  = carry[5];
  assign carry[6] = \adder_stage[6].genblk1.fa.cout ;
  assign Sum[6] = \adder_stage[6].genblk1.fa.sum ;
  assign \adder_stage[5].genblk1.fa.a  = A[5];
  assign \adder_stage[5].genblk1.fa.b  = B[5];
  assign \adder_stage[5].genblk1.fa.cin  = carry[4];
  assign carry[5] = \adder_stage[5].genblk1.fa.cout ;
  assign Sum[5] = \adder_stage[5].genblk1.fa.sum ;
  assign \adder_stage[4].genblk1.fa.a  = A[4];
  assign \adder_stage[4].genblk1.fa.b  = B[4];
  assign \adder_stage[4].genblk1.fa.cin  = carry[3];
  assign carry[4] = \adder_stage[4].genblk1.fa.cout ;
  assign Sum[4] = \adder_stage[4].genblk1.fa.sum ;
  assign \adder_stage[3].genblk1.fa.a  = A[3];
  assign \adder_stage[3].genblk1.fa.b  = B[3];
  assign \adder_stage[3].genblk1.fa.cin  = carry[2];
  assign carry[3] = \adder_stage[3].genblk1.fa.cout ;
  assign Sum[3] = \adder_stage[3].genblk1.fa.sum ;
  assign \adder_stage[2].genblk1.fa.a  = A[2];
  assign \adder_stage[2].genblk1.fa.b  = B[2];
  assign \adder_stage[2].genblk1.fa.cin  = carry[1];
  assign carry[2] = \adder_stage[2].genblk1.fa.cout ;
  assign Sum[2] = \adder_stage[2].genblk1.fa.sum ;
  assign \adder_stage[23].genblk1.fa.a  = A[23];
  assign \adder_stage[23].genblk1.fa.b  = B[23];
  assign \adder_stage[23].genblk1.fa.cin  = carry[22];
  assign Cout = \adder_stage[23].genblk1.fa.cout ;
  assign Sum[23] = \adder_stage[23].genblk1.fa.sum ;
  assign \adder_stage[22].genblk1.fa.a  = A[22];
  assign \adder_stage[22].genblk1.fa.b  = B[22];
  assign \adder_stage[22].genblk1.fa.cin  = carry[21];
  assign carry[22] = \adder_stage[22].genblk1.fa.cout ;
  assign Sum[22] = \adder_stage[22].genblk1.fa.sum ;
  assign \adder_stage[21].genblk1.fa.a  = A[21];
  assign \adder_stage[21].genblk1.fa.b  = B[21];
  assign \adder_stage[21].genblk1.fa.cin  = carry[20];
  assign carry[21] = \adder_stage[21].genblk1.fa.cout ;
  assign Sum[21] = \adder_stage[21].genblk1.fa.sum ;
  assign \adder_stage[20].genblk1.fa.a  = A[20];
  assign \adder_stage[20].genblk1.fa.b  = B[20];
  assign \adder_stage[20].genblk1.fa.cin  = carry[19];
  assign carry[20] = \adder_stage[20].genblk1.fa.cout ;
  assign Sum[20] = \adder_stage[20].genblk1.fa.sum ;
  assign \adder_stage[1].genblk1.fa.a  = A[1];
  assign \adder_stage[1].genblk1.fa.b  = B[1];
  assign \adder_stage[1].genblk1.fa.cin  = carry[0];
  assign carry[1] = \adder_stage[1].genblk1.fa.cout ;
  assign Sum[1] = \adder_stage[1].genblk1.fa.sum ;
  assign \adder_stage[19].genblk1.fa.a  = A[19];
  assign \adder_stage[19].genblk1.fa.b  = B[19];
  assign \adder_stage[19].genblk1.fa.cin  = carry[18];
  assign carry[19] = \adder_stage[19].genblk1.fa.cout ;
  assign Sum[19] = \adder_stage[19].genblk1.fa.sum ;
  assign \adder_stage[18].genblk1.fa.a  = A[18];
  assign \adder_stage[18].genblk1.fa.b  = B[18];
  assign \adder_stage[18].genblk1.fa.cin  = carry[17];
  assign carry[18] = \adder_stage[18].genblk1.fa.cout ;
  assign Sum[18] = \adder_stage[18].genblk1.fa.sum ;
  assign \adder_stage[17].genblk1.fa.a  = A[17];
  assign \adder_stage[17].genblk1.fa.b  = B[17];
  assign \adder_stage[17].genblk1.fa.cin  = carry[16];
  assign carry[17] = \adder_stage[17].genblk1.fa.cout ;
  assign Sum[17] = \adder_stage[17].genblk1.fa.sum ;
  assign \adder_stage[16].genblk1.fa.a  = A[16];
  assign \adder_stage[16].genblk1.fa.b  = B[16];
  assign \adder_stage[16].genblk1.fa.cin  = carry[15];
  assign carry[16] = \adder_stage[16].genblk1.fa.cout ;
  assign Sum[16] = \adder_stage[16].genblk1.fa.sum ;
  assign \adder_stage[15].genblk1.fa.a  = A[15];
  assign \adder_stage[15].genblk1.fa.b  = B[15];
  assign \adder_stage[15].genblk1.fa.cin  = carry[14];
  assign carry[15] = \adder_stage[15].genblk1.fa.cout ;
  assign Sum[15] = \adder_stage[15].genblk1.fa.sum ;
  assign \adder_stage[14].genblk1.fa.a  = A[14];
  assign \adder_stage[14].genblk1.fa.b  = B[14];
  assign \adder_stage[14].genblk1.fa.cin  = carry[13];
  assign carry[14] = \adder_stage[14].genblk1.fa.cout ;
  assign Sum[14] = \adder_stage[14].genblk1.fa.sum ;
  assign \adder_stage[13].genblk1.fa.a  = A[13];
  assign \adder_stage[13].genblk1.fa.b  = B[13];
  assign \adder_stage[13].genblk1.fa.cin  = carry[12];
  assign carry[13] = \adder_stage[13].genblk1.fa.cout ;
  assign Sum[13] = \adder_stage[13].genblk1.fa.sum ;
  assign \adder_stage[12].genblk1.fa.a  = A[12];
  assign \adder_stage[12].genblk1.fa.b  = B[12];
  assign \adder_stage[12].genblk1.fa.cin  = carry[11];
  assign carry[12] = \adder_stage[12].genblk1.fa.cout ;
  assign Sum[12] = \adder_stage[12].genblk1.fa.sum ;
  assign \adder_stage[11].genblk1.fa.a  = A[11];
  assign \adder_stage[11].genblk1.fa.b  = B[11];
  assign \adder_stage[11].genblk1.fa.cin  = carry[10];
  assign carry[11] = \adder_stage[11].genblk1.fa.cout ;
  assign Sum[11] = \adder_stage[11].genblk1.fa.sum ;
  assign \adder_stage[10].genblk1.fa.a  = A[10];
  assign \adder_stage[10].genblk1.fa.b  = B[10];
  assign \adder_stage[10].genblk1.fa.cin  = carry[9];
  assign carry[10] = \adder_stage[10].genblk1.fa.cout ;
  assign Sum[10] = \adder_stage[10].genblk1.fa.sum ;
  assign \adder_stage[0].genblk1.fa.a  = A[0];
  assign \adder_stage[0].genblk1.fa.b  = B[0];
  assign \adder_stage[0].genblk1.fa.cin  = Cin;
  assign carry[0] = \adder_stage[0].genblk1.fa.cout ;
  assign Sum[0] = \adder_stage[0].genblk1.fa.sum ;
endmodule